/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import BN from "bn.js";
import { ContractOptions } from "web3-eth-contract";
import { EventLog } from "web3-core";
import { EventEmitter } from "events";
import {
  Callback,
  PayableTransactionObject,
  NonPayableTransactionObject,
  BlockType,
  ContractEventLog,
  BaseContract,
} from "./types";

interface EventOptions {
  filter?: object;
  fromBlock?: BlockType;
  topics?: string[];
}

export type DailyAuthorizedInflationSet = ContractEventLog<{
  authorizedAmountWei: string;
  0: string;
}>;
export type FeePercentageChanged = ContractEventLog<{
  dataProvider: string;
  value: string;
  validFromEpoch: string;
  0: string;
  1: string;
  2: string;
}>;
export type FtsoRewardManagerActivated = ContractEventLog<{
  ftsoRewardManager: string;
  0: string;
}>;
export type FtsoRewardManagerDeactivated = ContractEventLog<{
  ftsoRewardManager: string;
  0: string;
}>;
export type GovernanceCallTimelocked = ContractEventLog<{
  selector: string;
  allowedAfterTimestamp: string;
  encodedCall: string;
  0: string;
  1: string;
  2: string;
}>;
export type GovernanceInitialised = ContractEventLog<{
  initialGovernance: string;
  0: string;
}>;
export type GovernedProductionModeEntered = ContractEventLog<{
  governanceSettings: string;
  0: string;
}>;
export type InflationReceived = ContractEventLog<{
  amountReceivedWei: string;
  0: string;
}>;
export type RewardClaimed = ContractEventLog<{
  dataProvider: string;
  whoClaimed: string;
  sentTo: string;
  rewardEpoch: string;
  amount: string;
  0: string;
  1: string;
  2: string;
  3: string;
  4: string;
}>;
export type RewardClaimsEnabled = ContractEventLog<{
  rewardEpochId: string;
  0: string;
}>;
export type RewardClaimsExpired = ContractEventLog<{
  rewardEpochId: string;
  0: string;
}>;
export type RewardsBurned = ContractEventLog<{
  amountBurnedWei: string;
  0: string;
}>;
export type RewardsDistributed = ContractEventLog<{
  ftso: string;
  epochId: string;
  addresses: string[];
  rewards: string[];
  0: string;
  1: string;
  2: string[];
  3: string[];
}>;
export type TimelockedGovernanceCallCanceled = ContractEventLog<{
  selector: string;
  timestamp: string;
  0: string;
  1: string;
}>;
export type TimelockedGovernanceCallExecuted = ContractEventLog<{
  selector: string;
  timestamp: string;
  0: string;
  1: string;
}>;
export type UnearnedRewardsAccrued = ContractEventLog<{
  epochId: string;
  reward: string;
  0: string;
  1: string;
}>;

export interface FtsoRewardManager extends BaseContract {
  constructor(
    jsonInterface: any[],
    address?: string,
    options?: ContractOptions
  ): FtsoRewardManager;
  clone(): FtsoRewardManager;
  methods: {
    accrueUnearnedRewards(
      _epochId: number | string | BN,
      _priceEpochDurationSeconds: number | string | BN,
      _priceEpochEndTime: number | string | BN
    ): NonPayableTransactionObject<void>;

    activate(): NonPayableTransactionObject<void>;

    active(): NonPayableTransactionObject<boolean>;

    autoClaim(
      _rewardOwners: string[],
      _rewardEpoch: number | string | BN
    ): NonPayableTransactionObject<void>;

    cancelGovernanceCall(
      _selector: string | number[]
    ): NonPayableTransactionObject<void>;

    claim(
      _rewardOwner: string,
      _recipient: string,
      _rewardEpoch: number | string | BN,
      _wrap: boolean
    ): NonPayableTransactionObject<string>;

    claimFromDataProviders(
      _rewardOwner: string,
      _recipient: string,
      _rewardEpochs: (number | string | BN)[],
      _dataProviders: string[],
      _wrap: boolean
    ): NonPayableTransactionObject<string>;

    claimReward(
      _recipient: string,
      _rewardEpochs: (number | string | BN)[]
    ): NonPayableTransactionObject<string>;

    claimRewardFromDataProviders(
      _recipient: string,
      _rewardEpochs: (number | string | BN)[],
      _dataProviders: string[]
    ): NonPayableTransactionObject<string>;

    claimSetupManager(): NonPayableTransactionObject<string>;

    closeExpiredRewardEpoch(
      _rewardEpoch: number | string | BN
    ): NonPayableTransactionObject<void>;

    deactivate(): NonPayableTransactionObject<void>;

    defaultFeePercentage(): NonPayableTransactionObject<string>;

    distributeRewards(
      _addresses: string[],
      _weights: (number | string | BN)[],
      _totalWeight: number | string | BN,
      _epochId: number | string | BN,
      _ftso: string,
      _priceEpochDurationSeconds: number | string | BN,
      _currentRewardEpoch: number | string | BN,
      _priceEpochEndTime: number | string | BN,
      _votePowerBlock: number | string | BN
    ): NonPayableTransactionObject<void>;

    enableClaims(): NonPayableTransactionObject<void>;

    executeGovernanceCall(
      _selector: string | number[]
    ): NonPayableTransactionObject<void>;

    feePercentageUpdateOffset(): NonPayableTransactionObject<string>;

    firstClaimableRewardEpoch(): NonPayableTransactionObject<string>;

    ftsoManager(): NonPayableTransactionObject<string>;

    getAddressUpdater(): NonPayableTransactionObject<string>;

    getClaimedReward(
      _rewardEpoch: number | string | BN,
      _dataProvider: string,
      _claimer: string
    ): NonPayableTransactionObject<{
      _claimed: boolean;
      _amount: string;
      0: boolean;
      1: string;
    }>;

    getContractName(): NonPayableTransactionObject<string>;

    getCurrentRewardEpoch(): NonPayableTransactionObject<string>;

    getDataProviderCurrentFeePercentage(
      _dataProvider: string
    ): NonPayableTransactionObject<string>;

    getDataProviderFeePercentage(
      _dataProvider: string,
      _rewardEpoch: number | string | BN
    ): NonPayableTransactionObject<string>;

    getDataProviderPerformanceInfo(
      _rewardEpoch: number | string | BN,
      _dataProvider: string
    ): NonPayableTransactionObject<{
      _rewardAmount: string;
      _votePowerIgnoringRevocation: string;
      0: string;
      1: string;
    }>;

    getDataProviderScheduledFeePercentageChanges(
      _dataProvider: string
    ): NonPayableTransactionObject<{
      _feePercentageBIPS: string[];
      _validFromEpoch: string[];
      _fixed: boolean[];
      0: string[];
      1: string[];
      2: boolean[];
    }>;

    getEpochReward(
      _rewardEpoch: number | string | BN
    ): NonPayableTransactionObject<{
      _totalReward: string;
      _claimedReward: string;
      0: string;
      1: string;
    }>;

    getEpochsWithClaimableRewards(): NonPayableTransactionObject<{
      _startEpochId: string;
      _endEpochId: string;
      0: string;
      1: string;
    }>;

    getEpochsWithUnclaimedRewards(
      _beneficiary: string
    ): NonPayableTransactionObject<string[]>;

    getExpectedBalance(): NonPayableTransactionObject<string>;

    getInflationAddress(): NonPayableTransactionObject<string>;

    getInitialRewardEpoch(): NonPayableTransactionObject<string>;

    getRewardEpochToExpireNext(): NonPayableTransactionObject<string>;

    getRewardEpochVotePowerBlock(
      _rewardEpoch: number | string | BN
    ): NonPayableTransactionObject<string>;

    getStateOfRewards(
      _beneficiary: string,
      _rewardEpoch: number | string | BN
    ): NonPayableTransactionObject<{
      _dataProviders: string[];
      _rewardAmounts: string[];
      _claimed: boolean[];
      _claimable: boolean;
      0: string[];
      1: string[];
      2: boolean[];
      3: boolean;
    }>;

    getStateOfRewardsFromDataProviders(
      _beneficiary: string,
      _rewardEpoch: number | string | BN,
      _dataProviders: string[]
    ): NonPayableTransactionObject<{
      _rewardAmounts: string[];
      _claimed: boolean[];
      _claimable: boolean;
      0: string[];
      1: boolean[];
      2: boolean;
    }>;

    getTokenPoolSupplyData(): NonPayableTransactionObject<{
      _lockedFundsWei: string;
      _totalInflationAuthorizedWei: string;
      _totalClaimedWei: string;
      0: string;
      1: string;
      2: string;
    }>;

    getTotals(): NonPayableTransactionObject<{
      _totalAwardedWei: string;
      _totalClaimedWei: string;
      _totalExpiredWei: string;
      _totalUnearnedWei: string;
      _totalBurnedWei: string;
      _totalInflationAuthorizedWei: string;
      _totalInflationReceivedWei: string;
      _lastInflationAuthorizationReceivedTs: string;
      _dailyAuthorizedInflation: string;
      0: string;
      1: string;
      2: string;
      3: string;
      4: string;
      5: string;
      6: string;
      7: string;
      8: string;
    }>;

    getUnclaimedReward(
      _rewardEpoch: number | string | BN,
      _dataProvider: string
    ): NonPayableTransactionObject<{
      _amount: string;
      _weight: string;
      0: string;
      1: string;
    }>;

    governance(): NonPayableTransactionObject<string>;

    governanceSettings(): NonPayableTransactionObject<string>;

    initialise(_initialGovernance: string): NonPayableTransactionObject<void>;

    newFtsoRewardManager(): NonPayableTransactionObject<string>;

    nextClaimableRewardEpoch(
      _rewardOwner: string
    ): NonPayableTransactionObject<string>;

    oldFtsoRewardManager(): NonPayableTransactionObject<string>;

    productionMode(): NonPayableTransactionObject<boolean>;

    receiveInflation(): PayableTransactionObject<void>;

    setDailyAuthorizedInflation(
      _toAuthorizeWei: number | string | BN
    ): NonPayableTransactionObject<void>;

    setDataProviderFeePercentage(
      _feePercentageBIPS: number | string | BN
    ): NonPayableTransactionObject<string>;

    setInitialRewardData(): NonPayableTransactionObject<void>;

    setNewFtsoRewardManager(
      _newFtsoRewardManager: string
    ): NonPayableTransactionObject<void>;

    switchToProductionMode(): NonPayableTransactionObject<void>;

    timelockedCalls(arg0: string | number[]): NonPayableTransactionObject<{
      allowedAfterTimestamp: string;
      encodedCall: string;
      0: string;
      1: string;
    }>;

    updateContractAddresses(
      _contractNameHashes: (string | number[])[],
      _contractAddresses: string[]
    ): NonPayableTransactionObject<void>;

    wNat(): NonPayableTransactionObject<string>;
  };
  events: {
    DailyAuthorizedInflationSet(
      cb?: Callback<DailyAuthorizedInflationSet>
    ): EventEmitter;
    DailyAuthorizedInflationSet(
      options?: EventOptions,
      cb?: Callback<DailyAuthorizedInflationSet>
    ): EventEmitter;

    FeePercentageChanged(cb?: Callback<FeePercentageChanged>): EventEmitter;
    FeePercentageChanged(
      options?: EventOptions,
      cb?: Callback<FeePercentageChanged>
    ): EventEmitter;

    FtsoRewardManagerActivated(
      cb?: Callback<FtsoRewardManagerActivated>
    ): EventEmitter;
    FtsoRewardManagerActivated(
      options?: EventOptions,
      cb?: Callback<FtsoRewardManagerActivated>
    ): EventEmitter;

    FtsoRewardManagerDeactivated(
      cb?: Callback<FtsoRewardManagerDeactivated>
    ): EventEmitter;
    FtsoRewardManagerDeactivated(
      options?: EventOptions,
      cb?: Callback<FtsoRewardManagerDeactivated>
    ): EventEmitter;

    GovernanceCallTimelocked(
      cb?: Callback<GovernanceCallTimelocked>
    ): EventEmitter;
    GovernanceCallTimelocked(
      options?: EventOptions,
      cb?: Callback<GovernanceCallTimelocked>
    ): EventEmitter;

    GovernanceInitialised(cb?: Callback<GovernanceInitialised>): EventEmitter;
    GovernanceInitialised(
      options?: EventOptions,
      cb?: Callback<GovernanceInitialised>
    ): EventEmitter;

    GovernedProductionModeEntered(
      cb?: Callback<GovernedProductionModeEntered>
    ): EventEmitter;
    GovernedProductionModeEntered(
      options?: EventOptions,
      cb?: Callback<GovernedProductionModeEntered>
    ): EventEmitter;

    InflationReceived(cb?: Callback<InflationReceived>): EventEmitter;
    InflationReceived(
      options?: EventOptions,
      cb?: Callback<InflationReceived>
    ): EventEmitter;

    RewardClaimed(cb?: Callback<RewardClaimed>): EventEmitter;
    RewardClaimed(
      options?: EventOptions,
      cb?: Callback<RewardClaimed>
    ): EventEmitter;

    RewardClaimsEnabled(cb?: Callback<RewardClaimsEnabled>): EventEmitter;
    RewardClaimsEnabled(
      options?: EventOptions,
      cb?: Callback<RewardClaimsEnabled>
    ): EventEmitter;

    RewardClaimsExpired(cb?: Callback<RewardClaimsExpired>): EventEmitter;
    RewardClaimsExpired(
      options?: EventOptions,
      cb?: Callback<RewardClaimsExpired>
    ): EventEmitter;

    RewardsBurned(cb?: Callback<RewardsBurned>): EventEmitter;
    RewardsBurned(
      options?: EventOptions,
      cb?: Callback<RewardsBurned>
    ): EventEmitter;

    RewardsDistributed(cb?: Callback<RewardsDistributed>): EventEmitter;
    RewardsDistributed(
      options?: EventOptions,
      cb?: Callback<RewardsDistributed>
    ): EventEmitter;

    TimelockedGovernanceCallCanceled(
      cb?: Callback<TimelockedGovernanceCallCanceled>
    ): EventEmitter;
    TimelockedGovernanceCallCanceled(
      options?: EventOptions,
      cb?: Callback<TimelockedGovernanceCallCanceled>
    ): EventEmitter;

    TimelockedGovernanceCallExecuted(
      cb?: Callback<TimelockedGovernanceCallExecuted>
    ): EventEmitter;
    TimelockedGovernanceCallExecuted(
      options?: EventOptions,
      cb?: Callback<TimelockedGovernanceCallExecuted>
    ): EventEmitter;

    UnearnedRewardsAccrued(cb?: Callback<UnearnedRewardsAccrued>): EventEmitter;
    UnearnedRewardsAccrued(
      options?: EventOptions,
      cb?: Callback<UnearnedRewardsAccrued>
    ): EventEmitter;

    allEvents(options?: EventOptions, cb?: Callback<EventLog>): EventEmitter;
  };

  once(
    event: "DailyAuthorizedInflationSet",
    cb: Callback<DailyAuthorizedInflationSet>
  ): void;
  once(
    event: "DailyAuthorizedInflationSet",
    options: EventOptions,
    cb: Callback<DailyAuthorizedInflationSet>
  ): void;

  once(event: "FeePercentageChanged", cb: Callback<FeePercentageChanged>): void;
  once(
    event: "FeePercentageChanged",
    options: EventOptions,
    cb: Callback<FeePercentageChanged>
  ): void;

  once(
    event: "FtsoRewardManagerActivated",
    cb: Callback<FtsoRewardManagerActivated>
  ): void;
  once(
    event: "FtsoRewardManagerActivated",
    options: EventOptions,
    cb: Callback<FtsoRewardManagerActivated>
  ): void;

  once(
    event: "FtsoRewardManagerDeactivated",
    cb: Callback<FtsoRewardManagerDeactivated>
  ): void;
  once(
    event: "FtsoRewardManagerDeactivated",
    options: EventOptions,
    cb: Callback<FtsoRewardManagerDeactivated>
  ): void;

  once(
    event: "GovernanceCallTimelocked",
    cb: Callback<GovernanceCallTimelocked>
  ): void;
  once(
    event: "GovernanceCallTimelocked",
    options: EventOptions,
    cb: Callback<GovernanceCallTimelocked>
  ): void;

  once(
    event: "GovernanceInitialised",
    cb: Callback<GovernanceInitialised>
  ): void;
  once(
    event: "GovernanceInitialised",
    options: EventOptions,
    cb: Callback<GovernanceInitialised>
  ): void;

  once(
    event: "GovernedProductionModeEntered",
    cb: Callback<GovernedProductionModeEntered>
  ): void;
  once(
    event: "GovernedProductionModeEntered",
    options: EventOptions,
    cb: Callback<GovernedProductionModeEntered>
  ): void;

  once(event: "InflationReceived", cb: Callback<InflationReceived>): void;
  once(
    event: "InflationReceived",
    options: EventOptions,
    cb: Callback<InflationReceived>
  ): void;

  once(event: "RewardClaimed", cb: Callback<RewardClaimed>): void;
  once(
    event: "RewardClaimed",
    options: EventOptions,
    cb: Callback<RewardClaimed>
  ): void;

  once(event: "RewardClaimsEnabled", cb: Callback<RewardClaimsEnabled>): void;
  once(
    event: "RewardClaimsEnabled",
    options: EventOptions,
    cb: Callback<RewardClaimsEnabled>
  ): void;

  once(event: "RewardClaimsExpired", cb: Callback<RewardClaimsExpired>): void;
  once(
    event: "RewardClaimsExpired",
    options: EventOptions,
    cb: Callback<RewardClaimsExpired>
  ): void;

  once(event: "RewardsBurned", cb: Callback<RewardsBurned>): void;
  once(
    event: "RewardsBurned",
    options: EventOptions,
    cb: Callback<RewardsBurned>
  ): void;

  once(event: "RewardsDistributed", cb: Callback<RewardsDistributed>): void;
  once(
    event: "RewardsDistributed",
    options: EventOptions,
    cb: Callback<RewardsDistributed>
  ): void;

  once(
    event: "TimelockedGovernanceCallCanceled",
    cb: Callback<TimelockedGovernanceCallCanceled>
  ): void;
  once(
    event: "TimelockedGovernanceCallCanceled",
    options: EventOptions,
    cb: Callback<TimelockedGovernanceCallCanceled>
  ): void;

  once(
    event: "TimelockedGovernanceCallExecuted",
    cb: Callback<TimelockedGovernanceCallExecuted>
  ): void;
  once(
    event: "TimelockedGovernanceCallExecuted",
    options: EventOptions,
    cb: Callback<TimelockedGovernanceCallExecuted>
  ): void;

  once(
    event: "UnearnedRewardsAccrued",
    cb: Callback<UnearnedRewardsAccrued>
  ): void;
  once(
    event: "UnearnedRewardsAccrued",
    options: EventOptions,
    cb: Callback<UnearnedRewardsAccrued>
  ): void;
}
